version: '3.7'

services:
  flow-beam:
    platform: linux/amd64
    image: rayvinflow/flow-beam:2.x
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    container_name: flow-beam
